### ISSUE TITLE
Internal Error (parameter-list-wrapping) on 0.17

### ISSUE THREAD

**Issue by SUPERCILEX** [shyiko/ktlint#165]
@shyiko #164 isn't fixed in 0.17. However, I've done more investigation and found a MCVE. With this `.editorconfig`:
```editorconfig
[*.{kt,kts}]
indent_size=unset
```
The following code produces the error:
```kt
fun foo(foo: Int
) {
    // ...
}
```

**Comment by shyiko** [comment]
Ah. That explains it. Fixed in [0.17.1](https://github.com/shyiko/ktlint/releases/tag/0.17.1).

**Comment by SUPERCILEX** [comment]
@shyiko are you sure you uploaded the update correctly? I still can't resolve it on jcenter... Really eager for the fix 😄

**Comment by shyiko** [comment]
It looks like https://issues.sonatype.org/browse/OSSRH-37894 all over again. https://oss.sonatype.org/content/repositories/releases/com/github/shyiko/ktlint/ contains 0.17.1 while http://repo1.maven.org/maven2/com/github/shyiko/ktlint/ does not. All we can do is wait.

**Comment by SUPERCILEX** [comment]
Aww, alright.

**Comment by SUPERCILEX** [comment]
Hey, I can confirm the fix! 👍
